nenvs: 4
nsize: 100000
minibatch: 256
start_noise: 0.5
end_noise: 0.01
training_frequency: 1
tau: 0.005
actor_lr_rate: 0.001
critic_lr_rate: 0.001
save_model_frequency: 100
start_training_size: 10000
train_steps: 250000
gamma: 0.99
logdir: "./logs/Ant(1)/ddpg/"
modeldir: "./models/Ant(1)/ddpg/"