nenvs: 20
nsize: 256
nminibatch: 4
nepoch: 4

vf_coef: 0.25
ent_coef: 0.00
clipgrad_norm: 0.5
clip_range: 0.20
lr_rate: 0.00025

save_model_frequency: 100
train_steps: 1000000

gamma: 0.98
tdlam: 0.95

timelimit: 150
logdir: "./logs/ppoclip/mt10/"
modeldir: "./models/ppoclip/mt10/"