nenvs: 4
nsize: 128
nminibatch: 1
nepoch: 1

vf_coef: 0.25
ent_coef: 0.00
clipgrad_norm: 0.5
lr_rate: 0.0007

save_model_frequency: 100
train_steps: 250000

gamma: 0.98
tdlam: 0.95

logdir: "./logs/HalfCheetah(1)/a2c/"
modeldir: "./models/HalfCheetah(1)/a2c/"