nenvs: 1
nsize: 25000
minibatch: 256
start_egreedy: 1.0
end_egreedy: 0.1
training_frequency: 4
update_frequency: 50
lr_rate: 0.001
save_model_frequency: 100
start_training_size: 5000
train_steps: 25000
gamma: 0.99
logdir: "./logs/dqn/CartPole/"
modeldir: "./models/dqn/CartPole/"